# Generated by Django 2.1 on 2018-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='The name of the game')),
                ('franchise', models.CharField(max_length=50, verbose_name='The franchise of the game')),
                ('publisher', models.CharField(max_length=50, verbose_name='The franchise of the game')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='User rating of the game from 1 to 10')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'db_table': 'games',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(to='api.Game')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'Genres',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
