# Generated by Django 2.1 on 2018-10-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181030_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='members',
            new_name='games',
        ),
    ]
