# Generated by Django 2.1 on 2018-10-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181030_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='games',
            new_name='members',
        ),
    ]
