# Generated by Django 2.1 on 2018-10-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181030_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='members',
            new_name='games',
        ),
    ]
