# Generated by Django 2.1 on 2018-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181030_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='overview',
            field=models.TextField(default='Este juego trata de un plomero que debe rescatar a una princesa secuestrada por un dragon', max_length=400, verbose_name='User rating of the game from 1 to 10'),
            preserve_default=False,
        ),
    ]
